version: '3'
services:
  webapp:
    container_name: 'garderie_webapp'
    image: openjdk:10-jdk
    depends_on:
      - garderie_db
    ports:
      - 8090:8080
    command: './gradlew bootRun  --project-cache-dir /root/.gradle'
    working_dir: /app
    volumes:
      - .:/app
      - ./docker_volumes/webapp/.gradle:/root/.gradle
    environment:
      POSTGRES_HOST: garderie_db
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: garderie
    restart: always

  build_webapp:
    image: openjdk:10-jdk
    command: './gradlew build --project-cache-dir /root/.gradle'
    working_dir: /app
    volumes:
      - .:/app
      - ./docker_volumes/build_webapp/.gradle:/root/.gradle

  garderie_db:
      image: postgres:9.6-alpine
      ports:
        - 5432:5432
      container_name: garderie_db
      volumes:
        - ./docker_volumes/garderie_db/pg_data:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: garderie
      restart: always

  seed_generator:
    image: python:3-slim
    container_name: seed_generator
    depends_on:
      - garderie_db
    volumes:
      - .:/app
      - ./docker_volumes/seed_generator/site-packages:/site-packages
    working_dir: /app
    command:
      sh scripts/generate_seed/run.sh
    environment:
      POSTGRES_HOST: garderie_db
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: garderie

  init_presence:
    image: groovy:2.4.15-jre8-alpine
    container_name: init_presence
    working_dir: /app
    depends_on:
      - garderie_db
    volumes:
      - .:/app
      - ./docker_volumes/init_presence/.grapes:/home/groovy/.groovy/grapes
    command: 'groovy scripts/init-presence.groovy'
    environment:
      POSTGRES_HOST: garderie_db
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: garderie
