version: '3'
services:
  webapp:
    container_name: 'garderie_webapp'
    image: openjdk:10-jdk
    depends_on:
      - postgres
    ports:
      - 8090:8080
    command: './gradlew bootRun'
    working_dir: /app
    volumes:
      - .:/app
      - ~/.gradle:/root/.gradle
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: garderie
    restart: always

  postgres:
      image: postgres:9.6-alpine
      ports:
        - 5432:5432
      container_name: garderie_db
      volumes:
        - ./docker_volumes/pg_data:/var/lib/postgresql/data
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        POSTGRES_DB: garderie
      restart: always

## add a service for seed-generator
## add a service for init-presence
